spring.application.name=registration


# database config
spring.datasource.url=jdbc:postgresql://localhost:5434/reg?useSSL=false
spring.datasource.username=postgres
spring.datasource.password=456123456


#JPA configurations
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Redis config
spring.data.redis.host=localhost
spring.data.redis.port=6379


# jwt
jwt.secret= dnskihrdrmv948scsh33riyxckfdgowuwruihwri34yt9vsnd4y439vhsdslk3w9
jwt.expiry-ms=86400000

#jsp config
spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp

#admin
admin.seed.email=admin@gmail.com
admin.seed.password=Admin@1234